config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show, :create, :destroy] do
    get "/start", to: "games#start"
  end
  post "/games/join", to: "games#join"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deck.rb
class Deck
  attr_reader :cards

  def deal_cards_to(amount, player)
    if player.class == Player
      player.cards = self.cards.slice!(0, 7)
      player.save
    end
  end

  def shuffle
    @cards = @cards.shuffle
  end

  def initialize
    @cards = []
    suits = ["clubs", "diamonds", "hearts", "spades"]
    numbers = ["ace", "2", "3", "4", "5", "6", "7", "8", "9", "10", "jack", "queen", "king"]
    
    suits.each do |suit|
      numbers.each do |number|
        @cards.push({suit: suit, number: number})
      end
    end
  end

  def self.new_from_json(cards_json)
    cards = JSON.parse(cards_json)["cards"]
    self.new.tap do |deck|
      deck.instance_variable_set("@cards", cards)
    end
  end

end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
  has_one :current_player, class_name: "Player"
  after_initialize :set_defaults, unless: :persisted?

  def deck
    @deck ||= Deck.new_from_json(self.deck_cards)
  end

  def start
    self.is_started = true
    for player in self.players do
      self.deck.deal_cards_to(7, player)
    end
    self.current_player = self.players[0]
    self.save
  end

  def set_defaults
    self.room_code = generate_room_code
    self.deck_cards = {cards: Deck.new.cards}.to_json
  end

  def generate_room_code
    chars = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
    code = ""
    6.times do 
      code += chars[rand(chars.size)]
    end
    if self.class.find_by(room_code: code)
      generate_room_code
    else
      return code
    end
  end

end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game

  def is_turn?
    self.game.current_player.id == self.id
  end

  def cards=(card_array)
    super({cards: card_array}.to_json)
  end

  def cards
    self[:cards] ? JSON.parse(self[:cards])["cards"] : []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  helper_method :current_player

  def create
    @game = Game.create
    p = @game.players.create
    session["player_id"] = p.id
    redirect_to game_path(@game.room_code)
  end

  def join
    @game = Game.find_by(room_code: params[:room_code])
    redirect_to games_path, alert: "Could not find room with that code!" if !@game

    if !@game.players.include?(current_player)
      p = @game.players.create
      session["player_id"] = p.id
    end
    redirect_to game_path(@game.room_code)
  end

  def show
    @game = Game.find_by(room_code: params[:id])
    if @game && @game.players.include?(current_player)
      render :show
    else
      redirect_to games_path, status: 404
    end
  end

  def start
    @game = Game.find_by(room_code: params[:game_id])
    if @game && @game.players.include?(current_player) && @game.players.size > 1
      @game.start
      current_player.reload
    end
    render :show
  end

  def current_player
    @current_player ||= Player.find_by(id: session["player_id"])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_card.html.erb
<div class="card">
  <%= image_tag "cards/#{card["number"]}_of_#{card["suit"]}.png" %>
  <% if current_player.is_turn? %>
    <%= button_to "Deal Card" %>
  <% end %>
</div>

app/views/games/index.html.erb
<h1>Go fish'in</h1>
<%= form_tag games_join_path do %>
  <label for="room_code">Enter Room Code To Join Game: </label>
  <%= text_area_tag :room_code %>
  <%= submit_tag "Join" %>
<% end %>

<%= button_to "Create New Game", games_path, method: "POST" %>

app/views/games/show.html.erb
<h1>Go Fishin Game</h1>
<h2><em>Room Code: <%= @game.room_code%></em></h2>
<h4>Players connected: <%= @game.players.size %></h4>

<% if @game.players.size > 1 %>
  <%= button_to "Start Game", game_start_path(@game.room_code), method: "get" if !@game.is_started %>
<%else%>
  <h4>Waiting on players</h4>
<% end %>

<% if @game.is_started %>
  <h4>Your cards: </h4>
  <%= render partial: "card", collection: @current_player.cards %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoFishin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>